# A config.yaml file is a simple, human-readable way to store configuration 
#data for your project. Instead of hardcoding things like file paths, hyperparameters, 
# or project settings inside your Python code, you store them here.

# It’s like giving your code a set of instructions from outside, so you don’t have to 
# touch the logic when you want to tweak something.

# Here we will set configuration for data ingestion
data_ingestion:
  bucket_name: "my_first_buck_95"
  bucket_file_name: "Hotel_Reservations_Data.csv"
  train_ratio: 0.8

# here we will give all the important columns which we got for categorical and continous data in jupyter notebook
data_preprocessing:
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest 
    - booking_status
  numerical_columns:
    - no_of_adults 
    - no_of_children 
    - no_of_weekend_nights
    - no_of_week_nights
    - lead_time 
    - arrival_year 
    - arrival_month
    - arrival_date
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
  skewnewss_threshold: 5
  no_of_features: 10